# Generated by Django 2.0.2 on 2018-03-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20180302_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='demoapp.Brands'),
        ),
    ]
